### ISSUE TITLE
Script crashing at initial launch after new install

### ISSUE THREAD

**Issue by JerkyChew899** [aelfakih/Manage-Chia-Farm#4]
Python 3.10, Windows 2022. I've modified the config files and installed the prerequisites. When trying to launch manage-chia-farm.py I receive the following errors and am not sure where the issue is:

> C:\Users\chia\Manage-Chia-Farm>manage-chia-farm.py
Traceback (most recent call last):
  File "C:\Users\chia\Manage-Chia-Farm\manage-chia-farm.py", line 27, in <module>
    from helpers import *
  File "C:\Users\chia\Manage-Chia-Farm\helpers.py", line 9, in <module>
    from PyInquirer import style_from_dict, Token, prompt
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\chia\AppData\Roaming\Python\Python310\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)

**Comment by aelfakih** [comment]
Looks like something is not installed.  Did you resolve the issue? Did you follow the installation steps?

**Comment by aelfakih** [comment]
I'm guessing it has to do with the way python environment variables are handled in windows 2022 as compared to windows 10. I have not tried it on that version of windows.

**Comment by aelfakih** [comment]
I will close this report since at this time I am not supporting windows 2022.  I do not have a license for it.  I will keep this version of windows in mind and if I get the chance to install it, I will support it as well. My apologies.
